Demo_shopping/Controllers/CartsController.cs
using Demo_shopping.Data;
using Demo_shopping.Helpers;
using Demo_shopping.Models;
using Demo_shopping.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Demo_shopping.Controllers
{
    public class CartsController : Controller
    {
        private readonly DataContext _context;

        public CartsController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<CartItemModel> cartItems = HttpContext.Session.GetJson<List<CartItemModel>>("Cart") ?? new List<CartItemModel>();
            CartItemViewModel cartVM = new()
            {
                cartItem = cartItems,
                GrandTotal = cartItems.Sum(x => x.Quantity * x.Price)
            };
            return View(cartVM);
        }
        public async Task<IActionResult> Add(int Id)
        {
            ProductsModel products = await _context.Products.FindAsync(Id);
            List<CartItemModel> cart = HttpContext.Session.GetJson<List<CartItemModel>>("Cart") ?? new List<CartItemModel>();
            CartItemModel cartItems = cart.Where(c => c.ProductId == Id).FirstOrDefault();

            if (cartItems == null)
            {
                cart.Add(new CartItemModel(products));
            }
            else
            {
                cartItems.Quantity += 1;
            }
            HttpContext.Session.SetJson("Cart", cart);
            TempData["success"] = "Add Item to Cart Successfully";

            return Redirect(Request.Headers["Referer"].ToString());
        }

        public async Task<IActionResult> Decrease(int Id)
        {
            List<CartItemModel> cart = HttpContext.Session.GetJson<List<CartItemModel>>("Cart");
            CartItemModel cartItems = cart.Where(c => c.ProductId == Id).FirstOrDefault();
            if (cartItems.Quantity > 1)
            {
                --cartItems.Quantity;
            }
            else
            {
                cart.RemoveAll(p => p.ProductId == Id);
            }
            if (cart.Count == 0)
            {
                HttpContext.Session.Remove("Cart");
            }
            else
            {
                HttpContext.Session.SetJson("Cart", cart);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Increase(int Id)
        {
            List<CartItemModel> cart = HttpContext.Session.GetJson<List<CartItemModel>>("Cart");
            CartItemModel cartItems = cart.Where(c => c.ProductId == Id).FirstOrDefault();
            if (cartItems.Quantity >= 1)
            {
                ++cartItems.Quantity;
            }
            else
            {
                cart.RemoveAll(p => p.ProductId == Id);
            }
            if (cart.Count == 0)
            {
                HttpContext.Session.Remove("Cart");
            }
            else
            {
                HttpContext.Session.SetJson("Cart", cart);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Remove(int Id)
        {
            List<CartItemModel> cart = HttpContext.Session.GetJson<List<CartItemModel>>("Cart");
            cart.RemoveAll(p => p.ProductId == Id);
            if (cart.Count == 0)
            {
                HttpContext.Session.Remove("Cart");

            }
            else
            {
                HttpContext.Session.SetJson("Cart", cart);

            }
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Clear()
        {
            HttpContext.Session.Remove("Cart");
            return RedirectToAction("Index");

        }
    }
}

Demo_shopping/Views/Carts/Index.cshtml
@using Demo_shopping.ViewModels
@model CartItemViewModel
<section id="cart_items">
    <div class="container">
        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li class="active">Shopping Cart</li>
            </ol>
        </div>
        <div class="table-responsive cart_info">
            <table class="table table-condensed">
                <thead>
                    <tr class="cart_menu">
                        <td class="image">Item</td>
                        <td class="description"></td>
                        <td class="price">Price</td>
                        <td class="quantity">Quantity</td>
                        <td class="total">Total</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.cartItem.Count > 0)
                    {
                        @foreach (var item in Model.cartItem)
                        {
                            <tr>
                                <td class="cart_product">
                                    <a href=""><img src="~/images/@item.Image" alt=""></a>
                                </td>
                                <td class="cart_description">
                                    <h4><a href="">@item.ProductName</a></h4>
                                </td>
                                <td class="cart_price">
                                    <p>@item.Price</p>
                                </td>
                                <td class="cart_quantity">
                                    <a class="btn btn-default btn-sm" asp-action="Increase" asp-controller="Carts" asp-route-id="@item.ProductId"> + </a>
                                    <input class="cart_quantity_input" type="text" name="quantity" value="@item.Quantity" autocomplete="off" size="2">
                                    <a class="btn btn-success btn-sm" asp-action="Decrease" asp-controller="Carts" asp-route-id="@item.ProductId"> - </a>
                                    <a class="btn btn-danger btn-sm" asp-action="Remove" asp-controller="Carts" asp-route-id="@item.ProductId"> Remove </a>
                                </td>
                                <td class="cart_total">
                                    <p class="cart_total_price">@Model.cartItem.Where(x => x.ProductId == @item.ProductId).Sum(x => x.Quantity * x.Price).ToString()</p>
                                </td>
                                <td class="cart_delete">
                                    <a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
                                </td>
                            </tr>
                        }
                        <tr rowspan="5">
                            <td colspan="6">Grand Total:<p class="cart_total_price">@Model.GrandTotal.ToString()</p></td>
                            <td><a class="btn btn-danger btn-sm" asp-action="Clear" asp-controller="Carts"> Clear </a></td>
                            @if (User.Identity?.IsAuthenticated ?? false)
                            {
                                <td><a class="btn btn-primary btn-sm" asp-action="Checkout" asp-controller="Checkout"> Checkout </a></td>
                            }
                        </tr>
                    }
                    else
                    {
                        <tr>
                            <td colspan="5">
                                <h4>Your Cart is Empty</h4>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section> <!--/#cart_items-->